### ISSUE TITLE
Database Goals for next sprint

### ISSUE THREAD

**Issue by Thejohnmeyers** [Salisbury-University/noaa-map#3]
-> Understand the current schema for the existing mbtiles database and the file hierarchy
->Decide whether it is best to enhance the existing schema or replace it with a completely customized one
-> If replace, begin to plan out the ER diagram for the new schema, and also plan out the new file structure
->Begin implementation

**Comment by darkfutrue** [comment]
**Completed Tasks**
Task ONE: Understand current schema and file hierarchy
Task TWO: Decided to replace the exiting Schema for a new customized one

**Current status**
Task THREE: Planning out the Schema for the new database AND creating python program to grab info from file system and place it into the new database

**Next Step**
Task FOUR: Begin implementing the database and populating it with the map tile data

**Comment by MarkSchwe** [comment]
**Completed Tasks: **
Task ONE: Understand current schema and file hierarchy
Task TWO: Decided to replace the exiting Schema for a new customized one
Task THREE: First version of a python program capable of grabbing file system information and placing it into a database has been finished. 

**Current Status**
Task FOUR: Begin implementing the database and populating it with the map tile data
